apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scalable-app-image-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefilepremium
  resources:
    requests:
      storage: 100Gi
