apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  selector:
      matchLabels:
        app: python
  replicas: 1
  template:
      metadata:
        labels:
            app: python
      spec:
        containers:
        - name: python
          image: chipfat/dsfc-python:v1
          imagePullPolicy: Always
          command: ['sh', '-c', 'git clone https://github.com/YoongiKim/CIFAR-10-images.git /images/CIFAR-10-images']
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          volumeMounts:
          - mountPath: "/images"
            name: scalable-app-image-data
        volumes:
        - name: scalable-app-image-data
          persistentVolumeClaim:
            claimName: scalable-app-image-data